cloud-1848 add DEFAULT_ADMIN_USERNAME
jboss-container-images/jboss-bpmsuite-7-openshift-image pull request #9
Opened 2017-08-09 15:06 UTC by bdecoste

2017-08-09 15:47 UTC, sutaakar commented
Should this fix be applied also to standalone controller [1]?

[1] https://github.com/jboss-container-images/jboss-bpmsuite-7-openshift-image/blob/bpmsuite70-dev/standalonecontroller/image.yaml

2017-08-10 14:12 UTC, errantepiphany requested changes
Yes, also to standalonecontroller. I just spoke with @bdecoste , and he'll be updating his PR. Thanks! :)

2017-08-14 13:41 UTC, errantepiphany approved these changes
Approved. Thanks Bill!

2017-08-14 14:26 UTC, rcernich submitted a review, later dismissed

2017-08-21 16:04 UTC, rcernich approved these changes

2017-08-21 16:05 UTC, merged